# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname cf1
#' @param dx A numeric value of time differences
#' @param alpha A vector of initial probabilities
#' @param rate A vector of transition rates
#' @param eps A value of tolerance error
#' @param ufactor A value of uniformization factor
#' @export
C_cf1pdf <- function(dx, alpha, rate, eps = 1.0e-8, ufactor = 1.01, log = FALSE) {
    .Call('_Rphsrm_C_cf1pdf', PACKAGE = 'Rphsrm', dx, alpha, rate, eps, ufactor, log)
}

#' @rdname cf1
#' @export
C_cf1cdf <- function(dx, alpha, rate, eps = 1.0e-8, ufactor = 1.01, lower = TRUE, log = FALSE) {
    .Call('_Rphsrm_C_cf1cdf', PACKAGE = 'Rphsrm', dx, alpha, rate, eps, ufactor, lower, log)
}

#' @rdname cf1
#' @export
C_cf1sample <- function(n, alpha, rate) {
    .Call('_Rphsrm_C_cf1sample', PACKAGE = 'Rphsrm', n, alpha, rate)
}

#' @rdname cf1
#' @export
C_cf1reform <- function(alpha, rate) {
    .Call('_Rphsrm_C_cf1reform', PACKAGE = 'Rphsrm', alpha, rate)
}

#' @rdname cf1
#' @export
C_cf1sojourn <- function(alpha, rate, f, b, t, eps = 1.0e-8, ufactor = 1.01) {
    .Call('_Rphsrm_C_cf1sojourn', PACKAGE = 'Rphsrm', alpha, rate, f, b, t, eps, ufactor)
}

#' EM step
#'
#' Execute one EM step for software reliability models.
#'
#' @param params A numeric vector for model parameters
#' @param data A faultdata
#' @param eps A numeric value for tolerance error.
#' @param ufactor A numeric value indicating the uniformization factor
#' @return A list with an updated parameter vector (param),
#' absolute difference of parameter vector (pdiff),
#' log-likelihood function for a given parameter vector (llf),
#' the number of total faults (total).
#' @export
em_cf1_emstep <- function(params, data, eps = 1.0e-8, ufactor = 1.01) {
    .Call('_Rphsrm_em_cf1_emstep', PACKAGE = 'Rphsrm', params, data, eps, ufactor)
}

